# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileIndex', models.CharField(max_length=128)),
                ('fileType', models.CharField(max_length=128)),
                ('fileId', models.CharField(max_length=128)),
                ('fileRemotePath', models.CharField(max_length=256)),
                ('fileMD5', models.CharField(blank=True, max_length=1024)),
                ('fileStatus', models.BooleanField(default=False)),
            ],
        ),
    ]
